from enum import Enum

CONSTANT_FOR_TEXT_REQUEST_API = '10kg Meat'
CONSTANT_INCORRECT_CASE_FOR_TEXT_REQUEST_API = 'Bad Request'

INDEX_FOR_GET_JSON_ERROR = 'message'

COSTANT_FOR_RETURN_ERROR_IN_VIEW = 'The params is not valid'


